package entity;

public enum AirplaneManufacturers {

    AIRBUS,
    ANTONOV,
    ATR_AIRCRAFT,
    BOEING,
    BOMBARDIER_AEROSPACE,
    COMAC,
    EMBRAER,
    LET_CUNOVICE,
    MITSUBISHI_AIRCRAFT_CORPORATION,
    UNITED_AIRCRAFT_CORPORATION,

}
